### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by ksawerykarwacki** [flyingpie/windows-terminal-quake#1]
Should i run this from WIndows Terminal or as a separate process? If i run it from Windows terminal then can I run it in the background somehow or do I need another tab for my regular work?

**Comment by flyingpie** [comment]
Hello @ksawerykarwacki! The latest version contains a tray icon, which removes the need to run a separate terminal. Let me know if that solves your problem!

![image](https://user-images.githubusercontent.com/1295673/63095599-f091be80-bf6b-11e9-8ac9-07c18d2b8945.png)

**Comment by ksawerykarwacki** [comment]
Now it works flawless, thanks! I may try to play with the code to keep original size of window and try to remove titlebar for full quake-like experience. Have you though about it?

**Comment by flyingpie** [comment]
@ksawerykarwacki Great! I haven't, cause I like my terminal fullscreen, but feel free to mess around :). Are you not using the tabs, that appear in the titlebar?

**Comment by ksawerykarwacki** [comment]
I just want to get rid of the minimize/maximize/close menu. I tried GWL_Style but without any results.

I forked your copy and added few things:
- when process is not found it spawns the new one
- size of the window is preserved
- when open window is forced to stay on top of other windows

I think it is not that bad as my first day with C# :)

I should probably add some configuration but at this point I'm not sure if it is still worth to pursue this or just refresh my long forgotten c++ and fork terminal itself. Do you plan to migrate this to native terminal code?

**Comment by flyingpie** [comment]
@ksawerykarwacki I would, though I'd like to do it through the process of making a spec first so it'll ultimately get merged into the master repo. I also want to make it configurable and whatnot.

So this is originally meant as a quick-and-dirty workaround to get a Quake-style into Windows Terminal and do some prototyping of different features before trying out a native feature.

**Comment by ksawerykarwacki** [comment]
@flyingpie Great! If you need any help let me know as I'm heavy user of quaked conemu and I have a lot of edge cases like screens with different scaling in single config etc. As for now I'm closing this one as there is no more issues :)
