### ISSUE TITLE
Suggestion: Use JSON5 for configuration file.

### ISSUE THREAD

**Issue by webbertakken** [flyingpie/windows-terminal-quake#104]
Currently when I'm editing the JSON configuration file, I see errors and warnings all over the file for every comment.

I will illustrate this with a screenshot. It happens the same for all WebStorm, Rider and VS Code:

![image](https://user-images.githubusercontent.com/20756439/139308017-30315f43-c201-45f7-8a55-2bbb2f71458c.png)

This makes it hard to spot warnings like mistyping `Oemtilde` with `OemTilde`.

My suggestion would be to move to [JSON5](https://json5.org/) for configuration files, so that comment are allowed, and part of the syntax.

**Comment by flyingpie** [comment]
@webbertakken So what about just supporting yaml instead? This would allow comments, and should work on most major editors.

It's nice to know that VS Code suggests the plugin right away, though.

**Comment by webbertakken** [comment]
Afaik YAML is natively supported in all IDEs, so there's that.

I feel YAMLs upside is that it's more concise and much easier to read once you're used to it while its downside is that people new to it may mess up both syntax and spacing. Maybe you're right and YAML would be the better option. But lets make sure we do have a definition file in that case as well.

Personally I have no preference between JSON5 or YAML.

**Comment by flyingpie** [comment]
@webbertakken Thank you for your thoughts on this, I really appreciate it.

I'll look into a YAML parser, and specifically see whether this works with VS Code as nicely as JSON does, when combined with a schema file. I'll also do some tests with other well-known editors, since I like having stuff "just work" without specific editors or addons.

**Comment by juventus18** [comment]
I noticed today that the `settings.json` file used directly for windows terminal settings does not produce errors for comments when using vscode, so it must be possible without changing the file extension or going to YAML.

I noticed the schema files for WT and w-t-q each reference a different base schema, maybe a place to start?

**Comment by flyingpie** [comment]
@juventus18 Could you tell us what VSCode is saying about the file format? It may be that you're using "jsonc", or  "JSON + Comments":

![image](https://user-images.githubusercontent.com/1295673/146640140-c6d74dfb-e1ab-407b-bb45-da7af1cc4c5c.png)

**Comment by juventus18** [comment]
@flyingpie yeah, when I open WT `settings.json` it auto-detects "JSON with comments". When I open `windows-terminal-quake.json` it auto-detects to plain "JSON". A little quirky, but it seems that simply renaming `windows-terminal-quake.json` to `settings.json` makes VSC auto-detect "JSON with comments" rather than "JSON".

The red lines did bother me a little bit before, but now that I know I can just manually switch, seems nbd (and a handy tidbit for other bothersome JSON files).

**Comment by webbertakken** [comment]
VS Code allows this for their own settings file. See also earlier references. 

It's not a good solution for any product that isn't vs code itself. Also editing that config in other IDEs will not auto-detect jsonc because it doesn't match the spec.

**Comment by allan-bonadio** [comment]
json5 is still a subset of JS itself.  So you can set your editor to JS for syntax when editing a file.  Also, it's a superset of JSON and JSONC and probably any 'json with comments' format MS uses, so a rename to .json5 is an easy way to upgrade files.

**Comment by flyingpie** [comment]
I've updated wtq to also look for ".jsonc" and ".json5" files (and we can easily add more extensions of course), so if you now use a file called "windows-terminal-quake.jsonc" and VS Code at least will automatically switch to "JSON with comments" highlighting.

**Comment by jmjoy** [comment]
Regardless of whether to use json5 or standardize jsonc, I think it is a good idea.

For `jsonc`, we should use extension name `jsonc`, not `json`.

**Comment by flyingpie** [comment]
> Regardless of whether to use json5 or standardize jsonc, I think it is a good idea.
> 
> For `jsonc`, we should use extension name `jsonc`, not `json`.

Yeah good point, I'll update the shipped/generated config file in the next update.

**Comment by flyingpie** [comment]
Current (v2) branch supports .json, .jsonc (the default) and .json5. Makes comments work correctly in at least Visual Studio Code.

I'm closing this issue, if anyone has any questions or suggestions, feel free to (re-)open!
