### ISSUE TITLE
Error opening terminal

### ISSUE THREAD

**Issue by Dominiquini** [flyingpie/windows-terminal-quake#106]
When I tried to start the application, this error appears:

`Error starting Windows Terminal Quake: Access is denied`

Log File:

[20211215.txt](https://github.com/flyingpie/windows-terminal-quake/files/7717597/20211215.txt)

This app worked fine the first time I tried, but is not working anymore!

Thanks

**Comment by couleurm** [comment]
Where is the location of windows-terminal-quake.exe at?

**Comment by Dominiquini** [comment]
> Where is the location of windows-terminal-quake.exe at?

I put it in this folder: "C:\Users\Rafael Dominiquini\AppData\Local\Programs\Windows Terminal Quake\windows-terminal-quake.exe"

I tried to put in another location, and the same error occurs!

**Comment by flyingpie** [comment]
@Dominiquini You can open the Windows Terminal just fine? Where is it located?

**Comment by Dominiquini** [comment]
> @Dominiquini You can open the Windows Terminal just fine? Where is it located?

Windows Terminal works just fine on my PC! It's located on "C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\wt.exe", but are links on "C:\Users\Rafael Dominiquini\AppData\Local\Microsoft\WindowsApps\wt.exe" and "system32". I can open on cmd!

**Comment by flyingpie** [comment]
Closing this for now, as it should be fixed in recent versions.

If anyone still encounters the issue, feel free to re-open or make a new one.
