### ISSUE TITLE
Toggling always switches back to the original virtual desktop (v1.2.0+)

### ISSUE THREAD

**Issue by tdy** [flyingpie/windows-terminal-quake#108]
As of v1.2.0, this can be reproduced as such:

1. Start WTQ on virtual desktop 2
1. Untoggle WTQ
1. Switch to virtual desktop 1
1. Toggle WTQ
    * **In v1.2.0+, it will automatically jump back to desktop 2**
    * In v1.1.1, it will stay on the current desktop 1

**Comment by flyingpie** [comment]
@tdy Could you try again with the latest preview (1.5.0)? I'm not able to reproduce the problem with that version at least.

**Comment by flyingpie** [comment]
I'm closing this issue, as it still seems to work properly with WTQ v2.

Feel free to re-open or open a new issue if you encounter the problem again!
