### ISSUE TITLE
Support multiple modifiers

### ISSUE THREAD

**Issue by amlamarra** [flyingpie/windows-terminal-quake#109]
Correct me if I'm wrong, but it seems like this does not support the use of multiple modifiers for hotkeys. For instance, I'd like to set my hotkey for toggling the terminal to Ctrl+Shift+Z.

**Comment by flyingpie** [comment]
@amlamarra Thank you for reaching out! Can you show me your config file? This should actually work just fine.

**Comment by flyingpie** [comment]
Could you try the following:

```json
"Hotkeys": [
    {
        "Modifiers": "Control,Shift",
        "Key": "Q"
    }
],
```

**Comment by amlamarra** [comment]
That works, thanks! Might I suggest adding it as an example to the documentation?

**Comment by flyingpie** [comment]
@amlamarra Done! :)
