### ISSUE TITLE
Fix scoop installation on Quake Documentation

### ISSUE THREAD

**Issue by vvirtues** [flyingpie/windows-terminal-quake#111]
Currently, the link there is https://github.com/flyingpie/windows-terminal-quake/blob/master/scoop/windows-terminal-quake.json, but this won't work because it isn't raw. Change to https://raw.githubusercontent.com/flyingpie/windows-terminal-quake/master/scoop/windows-terminal-quake.json for it to work

**Comment by flyingpie** [comment]
@vvirtues Fixed, thank you for reporting!
