### ISSUE TITLE
MSTerminal:  snapToGridOnResize= false.  Incompatible with windows-terminal-quake

### ISSUE THREAD

**Issue by mkanet** [flyingpie/windows-terminal-quake#114]
I'm not sure how to configure **windows-terminal-quake** to respect the Window position and size set by MS Terminal settings:

```
    "initialPosition": "962,0"
    "initialCols": 134,
    "initialRows": 26,
```

The only thing I can do is use `VerticalScreenCoverage` and `HorizontalScreenCoverage` in windows-terminal-quake; which isn't very granular.  I'm not sure what else to try.  Currently, I'm opening MS Terminal without windows-terminal-quake just so the window opens in the specific size and location I want.

If there isn't a way to do this, could you **please** add support for this?  I think it would be a very useful feature; especially since MS Terminal already supports `snapToGridOnResize= false`.

Thank you so much for your hard work and time!

**Comment by flyingpie** [comment]
@mkanet Thank you for reaching out! So if I understand correctly, you basically want windows-terminal-quake to not touch the size of Windows Terminal, and just handle the dropdown?

**Comment by mkanet** [comment]
Thanks for the quick reply.  Yes, that would be awesome!

**Comment by flyingpie** [comment]
@mkanet I've made a prerelease that adds a "KeepOriginalSize" setting:

```json
{
  "KeepOriginalSize": true
}
```

Not entirely happy with the naming yet, but this basically makes wtq not touch the size of the terminal (including if you manually resize after startup). So the name of the setting could change still.

Could you tell me whether this is what you were looking for?

You can try it either by downloading the release, or building the branch:
Release: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.5
PR: https://github.com/flyingpie/windows-terminal-quake/pull/115

Thanks!

**Comment by mkanet** [comment]
I think you're almost there!

When **wtq** launches, the window snaps to the side of the screen specified by `"HorizontalAlign": "Right"`.  It looks like `"KeepOriginalSize": true`  is **not** ignoring `"HorizontalAlign"`.  

I tried removing `"HorizontalAlign"` from the settings; but, it then just defaults to `center`.

Do you think that's the problem?

**Comment by flyingpie** [comment]
@mkanet Okay, so you want the position to stay wherever it started as well?

**Comment by mkanet** [comment]
Yes.  The position/size should be specified by MS Terminal.  Thank a million!!

**Comment by flyingpie** [comment]
@mkanet Okay, slightly different approach, instead of a new setting "KeepOriginalSize", I've added a toggle mode. Add this to the config file:

```json
{
  "ToggleMode": "Initial"
}
```

This doesn't touch the target position or size at all, whatsoever. It totally ignores where the cursor is, and lets you do all the moving and sizing.

Is this what you are looking for?

Here's the new release: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.5
Or build from the same branch as before.

**Comment by flyingpie** [comment]
@mkanet Thank you for your feedback! :)
