### ISSUE TITLE
Can you do the quake behavior for multiple apps?

### ISSUE THREAD

**Issue by neondeex** [flyingpie/windows-terminal-quake#118]
Can you do the quake behavior for multiple apps?

**Comment by flyingpie** [comment]
> Can you do the quake behavior for multiple apps?

Could you be a little more specific, provide an example maybe? :)

**Comment by neondeex** [comment]
Want to have quake behavior in apps like spotify, notion, file explorer that are persistent in virtual desktop changes

**Comment by flyingpie** [comment]
> Want to have quake behavior in apps like spotify, notion, file explorer that are persistent in virtual desktop changes

Got ya, and you'd want to have like different shortcuts for each app or something?

**Comment by neondeex** [comment]
> > Want to have quake behavior in apps like spotify, notion, file explorer that are persistent in virtual desktop changes
> 
> Got ya, and you'd want to have like different shortcuts for each app or something?

Thats right!

**Comment by flyingpie** [comment]
@neondeex That makes a lot of sense, I've already been messing around with a version that supports different terminals, but there's no reason to limit it to terminals at all. The main difference here is to actively support multiple application instances at _at the same time_.

There's currently 2 versions of this that I'm pondering:
- Bind one instance of wtq to a single app, that can be either a terminal, or spotify, or what have you, and give each one a different toggle shortcut, so you can change any setting per target app. Basically adding proper support to running multiple instances of wtq.
- Bind one instance of wtq to multiple applications of any application, and toggle within wtq between apps (like invisible tabs).

Do you have a clear preference for your use case? I'm leaning towards the latter, as it seems like a more straight-forward solution, and I'm not sure whether it's ever desirable to have multiple modals open at the same time. I see the window coming down as a "top most shelve", that only ever has 1 thing active.

Maybe we'd have a single shortcut for toggling the window open- and close, and use eg. ctrl + 1, 2, 3 to toggle between "tabs".

Also, I think that this would imply that the target app only ever has 1 instance, to keep things a bit simpler.

**Comment by neondeex** [comment]
> @neondeex That makes a lot of sense, I've already been messing around with a version that supports different terminals, but there's no reason to limit it to terminals at all. The main difference here is to actively support multiple application instances _at the same time_.
> 
> There's currently 2 versions of this that I'm pondering:
> 
> * Bind one instance of wtq to a single app, that can be either a terminal, or spotify, or what have you, and give each one a different toggle shortcut, so you can change any setting per target app. Basically adding proper support to running multiple instances of wtq.
> * Bind one instance of wtq to multiple applications of any application, and toggle within wtq between apps (like invisible tabs).
> 
> Do you have a clear preference for your use case? I'm leaning towards the latter, as it seems like a more straight-forward solution, and I'm not sure whether it's ever desirable to have multiple modals open at the same time. I see the window coming down as a "top most shelve", that only ever has 1 thing active.
> 
> Maybe we'd have a single shortcut for toggling the window open- and close, and use eg. ctrl + 1, 2, 3 to toggle between "tabs".
> 
> Also, I think that this would imply that the target app only ever has 1 instance, to keep things a bit simpler.

Im so sorry for not replying didn't see your comment but i do preffer the first option since in that way i will have direct access to the app that i want to open and the other one is almost like another virtual desktop and for that i can use vd

**Comment by neondeex** [comment]
@flyingpie

**Comment by flyingpie** [comment]
@neondeex I've been working to move the PR that was meant for handling different terminal types, to supporting multiple apps (including non-terminals).

It's a bit of a tricky rework, I'll ping you when I got a test version.

Since you convinced me that this is a feature I myself now want, it shouldn't take more than a couple days. :P

**Comment by flyingpie** [comment]
@neondeex As alluded to earlier, this is quite the rework, due to the current (v1) version being built around the concept that there is only ever 1 Windows Terminal process running. Not more, and certainly no other app types altogether.

So I'm restructuring everything into a new base that allows for this, and restoring features as I go.

If you like, you can take a look at [a current build](https://github.com/flyingpie/windows-terminal-quake/releases/tag/v2.0.0-pre1). I'm keeping track of things in a [discussion](https://github.com/flyingpie/windows-terminal-quake/discussions/119), feel free to chime in there as well.

https://github.com/flyingpie/windows-terminal-quake/assets/1295673/1bedd582-833a-4b7a-895a-f9d4de6d8ba7

**Comment by neondeex** [comment]
Amazing!
It works great! and i started using q-dir and is also amazing for my workflow
a few things to point out
- App auto-start and auto quake since i have to start the apps after the window-dropdown and then exec the keybing each restart
- Is there a way fo fix white q-dir white screen when opening?
- Where do I change quake size?
- Is there a way to specify a dfault display to quake a certain app?

Good work!

**Comment by flyingpie** [comment]
@neondeex Thank you for the kind words!

*App auto-start and auto quake since i have to start the apps after the window-dropdown and then exec the keybind each restart*
Totally agree, this part will be added soon, though it might take a while to get proper. For Windows Terminal specifically, there were some annoyances around starting the process.

*Is there a way to fix white q-dir white screen when opening?*
Can you post a screenshot or screencast of this? And you are on the most recent build?

*Where do I change quake size?*
You can't yet, it's coming in a future release. It will be in the wtq.jsonc file.

*Is there a way to specify a default display to quake a certain app?*
Could you elaborate a bit on this point? Would this also mean having multiple apps open at the same time?

**Comment by neondeex** [comment]
Ok about the flikering think you already fix it for q-dir in the new release havn't testeed yet
And about the last question for exapmle if specified i want to open the dropdown in a certain display even that my focus is in oter display it would be great if is easy to add otherwise I will have to change focus to that screen to use my graphic tablet for example

**Comment by flyingpie** [comment]
@neondeex Thank you for the info! Would you want to have multiple apps open at the same time, or still have at most 1 active?

1. Cursor is on display 1
2. Open app X that is tied to display 2
3. Open app Y that is not tied to a specific display -> Opens on display 1 (where cursor is)
4. Does app X close, or does it stay open? And if it stays open, what if the cursor moves to display 2 and you open app Y, should app X close then?

**Comment by neondeex** [comment]
Ty for the response
Only one active.

**Comment by flyingpie** [comment]
@neondeex Thanks for clarifying!

**Comment by flyingpie** [comment]
@neondeex I've added the setting to pick a monitor. This can be done globally, and per app.

Check it out, see if it works for you:
https://github.com/flyingpie/windows-terminal-quake/releases/tag/v2.0.0-pre4

**Comment by TechnicallyJoe** [comment]
Just weighing in here to say that this sounds freaking awesome.

I use my quake menu **extensively** and its the only reason i have been sticking to ConEmu. If i can use other apps quake style, i am going to be a very happy person.

**Comment by flyingpie** [comment]
@TechnicallyJoe Happy to hear it! Would you want to mention some apps you'd like to use this way? Maybe I can try them out for testing.

**Comment by TechnicallyJoe** [comment]
@flyingpie the most immediate ones that come to mind are MSTeams & Spotify. In some cases a browser window too (I use edge)

Generally i'd use it for those things where you either need to quickly reference or do something and push away. i.e. Put on a song, reference a piece of documentation or answer a question on msteams.

For longer things like any SaaS application, longer conversations / meetings etc. i wouldn't want to use it.

**Comment by flyingpie** [comment]
@TechnicallyJoe Thanks! Regarding apps like browsers, do you have multiple windows open where you'd only want to toggle one, or would it only ever be one window?

**Comment by TechnicallyJoe** [comment]
Multiple Windows, toggling only one :-)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by flyingpie** [comment]
@TechnicallyJoe Do you have any thoughts on how the window selection should work?

**Comment by TechnicallyJoe** [comment]
Same way i guess the Windows terminal/conemu works. If you open it through your app than it shows up when you quake it.

I would be alright with a solution where that worked kind of like opening multiple terminals in the conemu/WT. That would Also mean you would have 1 key bind for quaking the same Window and that window would have multiple tabs that could consider of Spotify, browser etc.

If you go with the one app/one quake keybind you would have to link then sonebod and then start them up through your app id imagine

Its tricky. But im not sure whats technically possible. We could have a chat somewhere if you would like and brain storm a little.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by flyingpie** [comment]
@TechnicallyJoe Not sure if you're aware, but there is an alpha build available of WTQ v2, where this behavior is partially implemented:
https://github.com/flyingpie/windows-terminal-quake/releases/tag/v2.0.0-pre3

And the accompanying discussion:
https://github.com/flyingpie/windows-terminal-quake/discussions/119

If you're feeling frisky, I'd love to see feedback :)

**Comment by flyingpie** [comment]
Version 2 is coming along nicely, I'm closing this issue.
