### ISSUE TITLE
When VerticalScreenCoverage is not 100, the width of the terminal is less than the width of the screen

### ISSUE THREAD

**Issue by baslas** [flyingpie/windows-terminal-quake#12]
Hello,

With v0.4, if I set the `VerticalScreenCoverage` to less than 100, my terminal looks like this:

![image](https://user-images.githubusercontent.com/45793121/90733069-5118b180-e2cc-11ea-8967-83a9a4b90992.png)

The tabs are not displayed because I used the focus mode of the Terminal Preview. This focus mode does not seem to affect the width issue.

Thanks for this project, I use it every day!

**Comment by flyingpie** [comment]
Closing this, please feel free to re-open if this is still an issue!
