### ISSUE TITLE
Allow using shortcuts without a modifier

### ISSUE THREAD

**Issue by evilmav** [flyingpie/windows-terminal-quake#127]
The JSON config schema seems to require a modifier to always be set in addition to a key if I read right. It would be nice if a shortcut key could be mapped without a modifier.

**Comment by flyingpie** [comment]
@evilmav Thank you for reporting this!

You can use shortcuts without modifiers, but you're totally right that it's heavily suggested otherwise.

I'll update the docs, could you test a configuration such as this (with your preferred key)?

```json
{
  "Apps": [
    {
      "HotKeys": [{ "Key": "D1" }]
      ...
    },
    ...
}
```

**Comment by flyingpie** [comment]
The documentation has been cleared up a bit, hopefully that's enough for now. Otherwise, feel free to re-open this issue.
