### ISSUE TITLE
windows-terminal-quake doesn't start both the terminal and itself. (exception thrown: process is null)

### ISSUE THREAD

**Issue by webbertakken** [flyingpie/windows-terminal-quake#13]
Hey @flyingpie, thanks a lot for creating this. I was so very happy to find this plugin. I'm sure I will be using this all the time like I did in Cmder.

I've downloaded `v0.5` (also  tried `v0.4`) and read the readme, but could not find how it is supposed to open both terminal and this plugin at the same time. I had hoped there would be some setting that allows the plugin to start with terminal automatically.

### Expected behaviour

Option 1:

- Open terminal executable
- See that terminal + quake style plugin work
- This clearly documented in the readme

Option 2;

- Open `windows-terminal-quake` executable
- See that terminal + quake style plugin work
- This clearly documented in the readme

#### First scenario worked perfectly;

- Open terminal
- Added executable and the config to `"C:\Users\(username)\"`
- Open `windows-terminal-quake.exe`
- See that it works! awesome.

#### But now I'd like the plugin to automatically start;

- Close terminal
- Open terminal again 
- See that quake style no longer works (which essentially just means that nothing was "installed")

#### So I'm thinking perhaps I should just open terminal with the executable;

- Close terminal
- Open `windows-terminal-quake.exe` 
- See a non-maximised terminal window without the plugin enabled.
- Open `windows-terminal-quake.exe` again with the window already open
- See that now it works.

### Considered solutions

I tried looking in the following places for clues how to make it work out of the box:

- The readme of this repository
- This plugins configuration
- The configuration file from Terminal

### Reason for starting both with 1 executable

- General convenience
- Opening it when clicking the terminal tab within an IDE will not work if there are two executable files to be called (I'm looking to replace Cmder now quake style is here for terminal)

![image](https://user-images.githubusercontent.com/20756439/90815470-0ed28d00-e32b-11ea-8d18-a86f24dfe5e1.png)

Thanks again for your great work.

**Comment by webbertakken** [comment]
Looking at the code I think it is already supposed to perform what I described above as "Expected behaviour, option 2".

I tried debugging the program and noticed that for me the process is already ended.

![image](https://user-images.githubusercontent.com/20756439/90825063-b0141000-e338-11ea-91a1-ddc5f431b3ae.png)

**Comment by webbertakken** [comment]
@flyingpie I know this doesn't happen in your case, but do you have any suggestions on how to solve this?

**Comment by flyingpie** [comment]
@webbertakken You mentioned that when you start the terminal app, it starts a process, that kicks off another process, then the first process exits. Is that correct?

If so, could you show me what the "intermediate" process is? I'm very confused by this, and why it would be different on my machine ™.

**Comment by webbertakken** [comment]
Correct.

Just to check if it's a one-of issue, I have just downloaded the latest (stable) version of terminal (from the store this time) after uninstalling the last version and downloaded the latest version from here too, but still observe the same behaviour.

I don't see why your OS or terminal would be different from mine either. The only thing I can think of is that my OS it's on top of Hyper-V but I do not think that would be related. So I guess I can't reliably answer your last question.

> If so, could you show me what the "intermediate" process is? 

Yes I'll see if I can find out some info about the signature of that process.

**Comment by webbertakken** [comment]
**Observations:**

The left hand side of the diff shows all accessible properties when the `wt` process is started from inside quake console whereas the right hand side shows the process information about the same process when it was already running (both cases: when started from a previous run of quake console or started as terminal standalone)

![image](https://user-images.githubusercontent.com/20756439/92416642-c276b200-f15e-11ea-8943-b42f762dc583.png)

This looks to be a permission issue that blocks Toggler from getting the `mainWindowHandle`.

I tried to work around this by:

- calling `process.`[Refresh()](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.refresh?view=netcore-3.1) as suggested [here](https://stackoverflow.com/a/16185802/3593896) without luck.
- calling `process.`[WaitForInputIdle](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforinputidle?view=netcore-3.1) as suggested in the official docs [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowhandle?view=netcore-3.1#remarks).
- reassinging `process` using
```csharp
process = Process.GetProcessesByName("WindowsTerminal").First();
```

In the last case I acquired access to the process finally. The wrapper is assigned to the process main window, which at this point is not maximised. It creates the console slider either way. I recorded a quick [video](https://www.youtube.com/watch?v=pmHGdiCvmkk) to illustrate this.

**Solution**

While typing all this out I tried the combination of the first and the last thing, which happened to work perfectly.

I'm expecting that solution should work for everyone, as all it does is remap the process to gain the proper permissions to access its properties.

I will update https://github.com/flyingpie/windows-terminal-quake/pull/14 to reflect the full solution.

**Comment by flyingpie** [comment]
@webbertakken Thank you for working on this some more.

With "race condition", do you mean merge conflict? I'm seeing a lot of changes that sort of conflict with changes that have been done in the mean time.

I've taken the non-conflicting changes and put that into a build.

This is working perfectly fine on my machine, could you see what happens on yours?

Here is the change: https://github.com/flyingpie/windows-terminal-quake/pull/21/files
Here is the release: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.8

**Comment by webbertakken** [comment]
Hey @flyingpie, and thank you for merging my PR!

When I said race condition I didn't mean a merge conflict. That post was made after the second commit last night. See the comment [here](https://github.com/flyingpie/windows-terminal-quake/pull/14/commits/27d342737d63682207706e297114b5d2d1724480#r484574177) pointing out the logging of all properties.

But the third commit was making a proper fix. It wasn't showing any merge conflicts but perhaps it was about making process a static variable in my PR.

I have checked `v0.8` pre-release. It works but I added 1 comment to that PR, because some of the logic shouldn't be necessary if the process is running initially.

Please let me know if you need anything and thanks again for making this awesome plugin!

**Comment by webbertakken** [comment]
Btw may I ask why you force pushed away my 3 commits that you merged into master? These fixes cost me quite a few hours to make and I'd appreciate it if you didn't just copy the changes into your own PR and merge it.

If you want me to replay the same changes in a PR, just let me know.

**Comment by flyingpie** [comment]
@webbertakken The PR merge and force push fuckery is basically all accidental, since I'm not too familiar with multiple git remotes yet, sorry for that. I definitely intend to ultimately use your PR with your code, I was just trying to make a version on top of the changes I made in the mean time.

That being said, could you make it so that the process doesn't become a static field, but is pull from a single method, like in the PR I made?

**Comment by webbertakken** [comment]
@flyingpie fair enough, I understand. 

I made these changes the way you mentioned in #22.

**Comment by flyingpie** [comment]
@webbertakken Thank you for the changes, looks very nice indeed!

Just to confirm, the code as per #22 is working on your machine without issue?
Cause it works over here, so that would be nice :)

One comment, this here line:
```csharp
Log.Logger.Warning($"Error: {ex.Message}\n{ex.StackTrace}");
```

Can be simplified to this:
```csharp
Log.Logger.Warning(ex, $"Error: {ex.Message}");
```

The Serilog logging library will take care of adding the stacktrace. In the case of a JSON formatter (not too useful for this app), the stack trace gets put into its own structured property, which makes it way easier to parse using eg. logstash or some other tool.

**Comment by webbertakken** [comment]
Oh really cool! I updated the logging statement.

I have tested one more time to double check and everything works from my side.

**Comment by flyingpie** [comment]
@webbertakken Thank you! Just merged the PR, so now we should have a version that works for the both of us :)

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.8
