### ISSUE TITLE
Cannot disable default hotkeys

### ISSUE THREAD

**Issue by TailyFair** [flyingpie/windows-terminal-quake#15]
Great app!

One thing is that I cannot disable default hotkeys `CTRL+~` and `CTRL+Q`, even if I have only `WIN+~` in configuration.

Default hotkeys are clashing with other hotkeys that I have and used to, besides I don't need 3 shortcuts to toggle Terminal.

My config:
```
{
	"HotKeys": [
		{
			"Modifiers": "Windows",
			"Key": "OemTilde"
		}
	],
	"Notifications": true,
	"Opacity": 90,
	"ToggleDurationMs": 0,
	"VerticalScreenCoverage": 100,
	"HorizontalScreenCoverage": 100
}
```

**Comment by flyingpie** [comment]
@TailyFair Thank you for reporting the issue!

Are the other options working as expected? Eg. Is the terminal slightly see-through (opacity 90), instant on/of (duration 0), etc.?

Where did you put the settings file? Have you tried restarting the app? Turning it off and on again :)

**Comment by TailyFair** [comment]
I tried restarting app, other options seems to work, but issue remains.

I glanced at code for a bit and it seems like default shortcuts are always added?
https://github.com/flyingpie/windows-terminal-quake/blob/master/windows-terminal-quake/Settings.cs#L114

**Comment by flyingpie** [comment]
@TailyFair I've fixed this in v0.7, could you check a look?

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.7

**Comment by TailyFair** [comment]
@flyingpie App does not want to launch at all in v0.7 and v0.8
I will try to verify this fix later.

**Comment by flyingpie** [comment]
@TailyFair There has been some work going on by @webbertakken regarding this issue (the app not starting), which seems to be fixed in v0.9. If you'd like to try that and tell us your findings, that'd be great!

**Comment by nlsantos** [comment]
FWIW, the default hotkeys are no longer always added for me (I prefer to use just Win-~; XKeymacs uses Ctrl-Q globally to toggle its functionality) since v0.7.

**Comment by flyingpie** [comment]
@nlsantos I've removed default hotkeys altogether, making it mandatory to have hotkeys configured in the settings file. Fresh downloads contain a settings file with hotkeys, but that might cause problems when someone upgraded from an older version.

**Comment by flyingpie** [comment]
Closing this issue, but feel free to leave a comment if the problem persists.
