### ISSUE TITLE
Alt + Tab

### ISSUE THREAD

**Issue by douglara** [flyingpie/windows-terminal-quake#17]
I'm using and loving it ❤️
I found one problem when giving and Alt +Tab
If i am terminal open and press Alt + Tab it doesn't exit correctly. 
When calling after Alt + Tab it exit and then i need to calling for second time

**Comment by flyingpie** [comment]
Hey @douglara Thank you for your feedback!

I've added a "HideOnFocusLost"-setting, defaults to "true", in this PR: https://github.com/flyingpie/windows-terminal-quake/pull/18.

There is a pre-compiled version here: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.6

Let me know what you think!

**Comment by douglara** [comment]
That's it, thanks friend 🔝
