### ISSUE TITLE
Docking and decoupling effect [feature request]

### ISSUE THREAD

**Issue by Aryevang** [flyingpie/windows-terminal-quake#24]
Hello,

I would like to avoid the effect of docking and decoupling of the panel and just let the panel drop.

This effect should have an option in the configuration file to activate/deactivate it.

Regards

**Comment by flyingpie** [comment]
@Aryevang Could you try these settings (other than the ones you already use):

```json
{
	"HorizontalScreenCoverage": 100.5,
	"VerticalScreenCoverage": 99
}
```

I'm curious to know whether that disables the "docking"-effect you describe.

Let me know your findings!

**Comment by Aryevang** [comment]
Hello @flyingpie,

Thank you for your quick response. This configuration actually works for me. A simple and elegant solution.

Regards.
