### ISSUE TITLE
[feature request] Choice to show it left/right aligned

### ISSUE THREAD

**Issue by bsides** [flyingpie/windows-terminal-quake#26]
Right now it appears centralized but, if anyone is like me and use the start bar anchored to the right, it will show the terminal below it, which isn't very nice. Instead, if I could adjust it by left aligning it (and then ajust its width) it would be perfect.

Thank you!

**Comment by flyingpie** [comment]
Hello @bsides, thank you for your feedback!

Could you include a screenshot of the problem and maybe a quick sketch/annotation of how you'd want it to work instead?

Thanks!

**Comment by bsides** [comment]
Sure thing @flyingpie 

Look at the image in the right
![image](https://user-images.githubusercontent.com/87631/94893609-fb542f00-045d-11eb-972d-dde11a9f1522.png)

I have two monitors, both set up to have the task bar (or start bar) to the right. The guake console aligns itself to the middle of the screen but doesn't take the bar width into the account, rendering itself below the bar. Now, an easy fix would be to have an option to not centralize the bar, but to align to the left (or right) and then the user can correct its width. The other fix would be to account the bar to make the center calculation, which could be an extra.

I draw something too, hopefully it's good enough 😅
![guake-windows-terminal](https://user-images.githubusercontent.com/87631/94894279-694d2600-045f-11eb-8086-a2925d534c9a.png)

**Comment by flyingpie** [comment]
@bsides Check out release v0.10: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.10

It has a "HorizontalAlign" setting: https://github.com/flyingpie/windows-terminal-quake/blob/b2c1e7b4e8be11847e34de5fed8a8b7ba6c5e2c3/windows-terminal-quake/windows-terminal-quake.json#L30

Left:
![image](https://user-images.githubusercontent.com/1295673/95656847-467ed980-0b11-11eb-87a4-2bff809c30d0.png)

Center:
![image](https://user-images.githubusercontent.com/1295673/95656889-8645c100-0b11-11eb-8310-c829f41e76bc.png)

Right:
![image](https://user-images.githubusercontent.com/1295673/95656866-6d3d1000-0b11-11eb-9680-cb67d1c5cc6c.png)

**Comment by bsides** [comment]
Awesome, will test it out today! Thanks!

**Comment by bsides** [comment]
Sorry for not confirming before, it works! The only issue I have right now is that I use Windows Terminal Preview and Quake one uses the regular release. Thanks for the feature!
