### ISSUE TITLE
[feature request] Vertical offset

### ISSUE THREAD

**Issue by nlsantos** [flyingpie/windows-terminal-quake#27]
I use Cairo Desktop on top of Windows; it displays a menu bar at the top of the screen, similar to macOS and GNOME. By default, the terminal window's tabs are obscured by it.

![image](https://user-images.githubusercontent.com/4997190/95061383-1e1c6700-072e-11eb-8ac4-c36dc3caf437.png)

It would be personally useful if there was a way to specify a vertical offset to the exposed terminal window, or if WTQ took the desktop's boundaries into consideration when toggling the window's visibility (maximized windows don't obscure Cairo's menu or task bars; i.e., CD sets boundaries correctly, so that info can be relied on).

**Comment by flyingpie** [comment]
@nlsantos Thank you for your feedback :)

Check out release v0.10: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.10

with the "VerticalOffset"-setting: https://github.com/flyingpie/windows-terminal-quake/blob/b418900b4e51ad6979156f43c7a2b99e23cf743e/windows-terminal-quake/windows-terminal-quake.json#L26

![image](https://user-images.githubusercontent.com/1295673/95657244-b9894f80-0b13-11eb-97d5-3f984f4de912.png)

Let me know what you think!

**Comment by nlsantos** [comment]
Suh-weet!

![image](https://user-images.githubusercontent.com/4997190/95662986-c3d83780-0b6d-11eb-82d9-3db9d9adf6b6.png)

(Currently using a value of 20.)

Thanks for implementing it so quickly!

**Comment by flyingpie** [comment]
You're welcome, thank you for confirming it works for you :)
