### ISSUE TITLE
Hide on focus lost false still hides behind windows

### ISSUE THREAD

**Issue by avere001** [flyingpie/windows-terminal-quake#32]
Currently setting `"HideOnFocusLost": false` is not enough to keep the terminal from going behind windows. 

As a workaround I have added the keybinding to windows terminal `{ "command": { "action": "toggleAlwaysOnTop" }, "keys": "ctrl+shift+q" }`. This is a sufficient workaround for me, but I have to remeber to hit that key combo when I first start windows terminal quake. 

Can you make it so setting hide on focus lost to false also sets windows terminal quake to be always on top?

**Comment by flyingpie** [comment]
@avere001 Thank you for your suggestion!

I've added this to v0.11: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.11

It's a setting called "AlwaysOnTop": https://github.com/flyingpie/windows-terminal-quake#always-on-top

Let me know whether this works for you :)

**Comment by flyingpie** [comment]
Fixed in v0.11.
