### ISSUE TITLE
Doesn't work from a folder with spaces in the name

### ISSUE THREAD

**Issue by aaronasmith** [flyingpie/windows-terminal-quake#36]
I modified Settings and Logging to 
Path.Combine(Path.GetDirectoryName(new Uri(typeof(Settings).Assembly.Location).LocalPath), "windows-terminal-quake.json")
and it was working.

Also, I'm trying to run from a folder in Program Files, and things seem pretty broken, such as it doesn't reload the settings automatically.  Probably due to permissions in that folder.

**Comment by flyingpie** [comment]
@aaronasmith Will be fixed with the next release, thank you for reporting!
