### ISSUE TITLE
Feature request: show version in tray

### ISSUE THREAD

**Issue by vertti** [flyingpie/windows-terminal-quake#38]
I don't want to remember which version of this companion I have installed. It would be great if hovering your mouse over the Tray icon would show version number. Now it says "Windows Terminal Quake", instead it could show "Windows Terminal Quake v0.11".

Thanks for the nice utility!

**Comment by flyingpie** [comment]
@vertti Part of the next release, thank you for your feedback!

![image](https://user-images.githubusercontent.com/1295673/103433716-8fb56580-4bf6-11eb-980e-81e358a0fdd9.png)
