### ISSUE TITLE
Feature request: add option to start hidden

### ISSUE THREAD

**Issue by dfyx** [flyingpie/windows-terminal-quake#42]
Currently when starting `windows-terminal-quake`, I immediately get a (almost?) full screen terminal window (even though that doesn't match my settings at all). I'd love to have an option to not show the terminal when `windows-terminal-quake` starts so I can put it in my autostart.

**Comment by flyingpie** [comment]
@dfyx As with your other one, great suggestion! I'll try to include this with the next release.

**Comment by flyingpie** [comment]
@dfyx Comes in the next release, which I'm finishing up right now. Look for the "StartHidden" setting:

```json
{
    "StartHidden": true
}
```
