### ISSUE TITLE
Feature request: add option to select monitor

### ISSUE THREAD

**Issue by dfyx** [flyingpie/windows-terminal-quake#43]
Currently, using the hotkey causes the terminal appear on the monitor where the mouse cursor is. It would be nice to have an option to set an integer that identifies which monitor the terminal should appear on with `null` being the current behavior.

**Comment by flyingpie** [comment]
@dfyx Great suggestion! I'll look into this for a coming release soon :)

**Comment by flyingpie** [comment]
@dfyx Comes in the next release, which I'm finishing up right now. Look for the "PreferMonitor" and "MonitorIndex" settings:

```jsonc
{
	// What monitor to preferrably drop the terminal
	// "WithCursor" (default), "Primary" or "AtIndex"
	"PreferMonitor": "AtIndex",

	// If "PreferMonitor" is set to "AtIndex", this setting determines what monitor to choose.
	// Zero based, eg. 0, 1, etc.
	"MonitorIndex": 0
}
```
