### ISSUE TITLE
When used with vs code shortcut terminal focus shortcut hijacked

### ISSUE THREAD

**Issue by rsJames-ttrpg** [flyingpie/windows-terminal-quake#44]
When used alongside vscode with the shortcuts   
  ```
{ "key": "ctrl+`", "command": "workbench.action.terminal.focus"},
{ "key": "ctrl+`", "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus"}
```
The quake terminal is called using ctrl+` instead of the vscode terminal panel despite them being different shortcuts.
TBH I like it, it just isn't expected behaviour.

**Comment by flyingpie** [comment]
@jackomayo Thank you for your comment! I'm not entirely sure if I understand you correctly though, is the point that:

- VS Code has ctrl+~ set for opening the built-in terminal
- WinTerm Quake has ctrl+~ set for toggling Windows Terminal
- When VS Code is open, and you press ctrl+~, Windows Terminal gets precedence over VS Code

Correct?

**Comment by aleybe** [comment]
Hi @rsJames-ttrpg and @flyingpie please take a look at #77  when you have a chance :)

**Comment by flyingpie** [comment]
PR is going through last bits of review, and will be part of v1.2.0 (with thanks to @aleybe).
