### ISSUE TITLE
Fails to start from a directory containing spaces in the name

### ISSUE THREAD

**Issue by dangoodman** [flyingpie/windows-terminal-quake#46]
v0.11 fails with `Cannot start: "Object reference not set to an instance of an object"` when launched from a directory containing a space char like `C:/Program Files/wtq` or `C:/Windows Terminal Quake`. Starts fine from `C:/wtq`.

![wtq-start-fail](https://user-images.githubusercontent.com/345718/100459982-d8519e80-30df-11eb-8db7-6cf911895adb.png)

**Comment by flyingpie** [comment]
@dangoodman Thank you for reporting this!

I'm working on a release where I'll include a fix for this.

**Comment by dangoodman** [comment]
Cool! Looking forward.

**Comment by flyingpie** [comment]
@dangoodman Will be fixed in the next release, thanks to [aaronasmith](https://github.com/aaronasmith) and [shrddr](https://github.com/shrddr)).
