### ISSUE TITLE
Trying to figure out how to pass arguments to windows terminal via this app

### ISSUE THREAD

**Issue by NikhilSaini38** [flyingpie/windows-terminal-quake#52]
So here is the use case.

I am trying to create a context menu entry for opening windows-terminal-quake in the selected directory, But I cannot figure out how and if we can pass arguments to the windows terminal for the working directory.

**Comment by flyingpie** [comment]
@NikhilSaini38 Thank you for your comment!

I've added this to release 1.1, which can be downloaded here:
https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.1

The PR is here, you need to get that branch if you'd like to make a build yourself:
https://github.com/flyingpie/windows-terminal-quake/pull/53

Let me know if that solves the issue!
