### ISSUE TITLE
Odd behaviour when ToggleDurationMs < ToggleAnimationFrameTimeMs

### ISSUE THREAD

**Issue by chessmango** [flyingpie/windows-terminal-quake#54]
I understand that by definition `ToggleAnimationFrameTimeMs` has a lower bound of 15 and defines the lower bound for `ToggleDurationMs` (granted I didn't quite catch this at first and trial-and-errored my way around for a while)

However, the terminal window is effectively a normal (albeit transparent and whatever else is configured) window when toggled in this state. Not sure whether worth looking into/fixing whatsoever, considering this is unsupported anyway, but just thought I'd bring it up regardless - please close this if `wontfix` :)

That said, comments in the sample `windows-terminal-quake.json` might be better expanded about the caveats here, so for example:

```
// How long the toggle up/down takes in milliseconds. The lowest value possible for this is defined by ToggleAnimationFrameTimeMs below
"ToggleDurationMs": 250,
```

Thanks for your work, and for the great release! Super glad to see the 1.0 milestone :D

**Comment by flyingpie** [comment]
@chessmango Thank you for your comment! :)

I've added a change here: #55. That basically caps the value of "ToggleDurationMs" to 15 and up.
The PR is part of prerelease 1.1: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.1

I think this solves the weird behavior you were talking about.

Please let me know if you find the same thing, and thanks again for taking the time to leave a comment ❤️
