### ISSUE TITLE
Start on preferred monitor in AtIndex mode?

### ISSUE THREAD

**Issue by syncore** [flyingpie/windows-terminal-quake#56]
Hey there, thanks for this software 👍. I find it very useful when I am on Windows. I was wondering if you plan on adding support to allow the application to start on the preferred monitor when it is in `AtIndex` mode? I quickly hacked this in [here](https://github.com/syncore/windows-terminal-quake/commit/9895716914f665be6a38a235259a2674293820bb) but perhaps there is a better/more elegant way.

Anyway, thank you again - cheers 🍻

**Comment by flyingpie** [comment]
@syncore Thank you for your feedback, Sorry for the late response. I'm planning to have this in the next release. Could you turn this into a PR so your name can be in the contributors list?

**Comment by flyingpie** [comment]
@syncore I (semi-accidentally) fixed this while fixing another issue (#71), it should work as expected in the latest release:

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

**Comment by syncore** [comment]
@flyingpie sounds good, glad you fixed it - I've moved to Linux full-time and no longer have access to Windows. I can close this issue if you want.
