### ISSUE TITLE
Install via scoop fails

### ISSUE THREAD

**Issue by Gerboa** [flyingpie/windows-terminal-quake#59]
Running the command line `scoop install https://github.com/flyingpie/windows-terminal-quake/blob/master/scoop/windows-terminal-quake.json` fails with the error:

>ConvertFrom-Json: C:\Users\\**********\scoop\apps\scoop\current\lib\manifest.ps1:25
Line |
  25 |      $str | convertfrom-json
     |             ~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
>
>Couldn't find manifest for 'https://github.com/flyingpie/windows-terminal-quake/blob/master/scoop/windows-terminal-quake.json'.

**Comment by jsonMartin** [comment]
I had the same error

**Comment by Deliganli** [comment]
please see https://github.com/flyingpie/windows-terminal-quake/issues/62

**Comment by flyingpie** [comment]
Fixed, thanks to @Deliganli.
