### ISSUE TITLE
gui and mouse hanging/lag

### ISSUE THREAD

**Issue by exitdown** [flyingpie/windows-terminal-quake#6]
after about 3 hours or so or repeated (50-60+) minimise/unminimise on windows 1904.21 (slow ring) with wsl2 the gui and mouse starts lagging and hanging similarly to how heavy i/o wait can effect the windows gui. isolation has shown its not the windows terminal (v0.8) and not wsl2 specificly (doesnt do it without quake app running) 

noones reported it so im assuming its just me. im running a surface pro 7  i7 16gig  and no other significant apps other than chrome. 

just thought id mention it in case im not the only one experiencing this - i suspect it could be a result of the pre release version of windows potentially, but anyway just documenting just in case :)

thanks!

**Comment by flyingpie** [comment]
@exitdown Thank you for the feedback! Does this by any chance only happen when you're on battery?

**Comment by exitdown** [comment]
no worries! it seems to do it  on charge as well - but you might be right about power management being related - surface pro 7 does have some aggressive power management settings, ill investigate further :)
