### ISSUE TITLE
window swaps monitor during closing animation

### ISSUE THREAD

**Issue by rmobis** [flyingpie/windows-terminal-quake#64]
If you open the terminal on one monitor, move your mouse to another monitor and press the hotkey to close it, the whole window is moved to the second monitor and the animation is player there.

Caching the monitor it opened on and then using that info on the closing animation should fix it.

**Comment by flyingpie** [comment]
@rmobis Thank you for the suggestion! I'll try to include this in the next release :)

**Comment by flyingpie** [comment]
@rmobis This is fixed through another issue, the screen where the terminal should open/close is now determined only on animation start.

I'd love to know if the latest release fixes it on your side too :)

**Comment by flyingpie** [comment]
Just took 3 years, but it's fixed in the latest release [2.0.9](https://github.com/flyingpie/windows-terminal-quake/releases/tag/v2.0.9).

**Comment by rmobis** [comment]
Regardless of how long it took, I appreciate it. I'll test it and let you know of the outcome. Thanks.
