### ISSUE TITLE
Should open Windows Terminal if not already started

### ISSUE THREAD

**Issue by vertti** [flyingpie/windows-terminal-quake#68]
Feature Request: I've put windows-terminal-quake to startup directory. So I'd love that it would start Windows Terminal if one is not already running. Not it just fails with a warning popup.

**Comment by flyingpie** [comment]
Hello @vertti, thank you for reporting this issue! This should actually already happen, could you provide the warning to see why wtq is not starting wt?

**Comment by vertti** [comment]
![cannotfind](https://user-images.githubusercontent.com/557751/110775601-c4354580-8267-11eb-8f15-98c5f76d4e8c.JPG)

That is what pops up when starting the quake 1.1.1 when I do not have Windows Terminal running. If I start Windows Terminal my self and after that the quake, everything works.

**Comment by flyingpie** [comment]
@vertti That's weird, what happens if you enter "wt" on the command line?

**Comment by flyingpie** [comment]
Also, I think this might be the same issue as reported here: #61. Fellow fmiqbal points out that repairing the Windows Terminal installation fixed the issue. He also wasn't able to run "wt" separately, so I'd like to know whether that does work on your machine.

**Comment by vertti** [comment]
Running `C:\Users\vertti\AppData\Local\Microsoft\WindowsApps\wt.exe` from command line works. I also tried running the Settings -> Apps -> Windows Terminal -> Repair. Still get the error from quake if Windows Terminal is not already running.

**Comment by flyingpie** [comment]
@vertti I've uploaded a new release with a new setting called "WindowsTerminalCommand", which controls the actual command that is used to start Windows Terminal, if it isn't running already.

Could you try to run this version with a setting such as:

```json
{
	"WindowsTerminalCommand": "C:\\Users\\vertti\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe"
}
```

I'm not sure why the app isn't finding wt.exe (which is the default command), but perhaps we can find something by messing around with the command.

It's release 'windows-terminal-quake-1.2.0-2021-04-30_1752.zip' here:

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

**Comment by juventus18** [comment]
sounds like you need to put windows terminal folder into your `PATH` env variable

**Comment by flyingpie** [comment]
@juventus18 True, but as far as I know, shouldn't that be done by the Windows Terminal installation?

**Comment by untoreh** [comment]
can this be extended to allow terminals other than Windows Terminal?

**Comment by flyingpie** [comment]
@untoreh It should, which one are you wanting to use?

**Comment by untoreh** [comment]
@flyingpie wezterm

**Comment by flyingpie** [comment]
@untoreh There is currently some Windows Terminal-specific stuff going on, but I don't see too much of a problem adding support for this.

Though, it's a little off-topic for this issue, could you open a new one with that specific feature request?

**Comment by justinledwards** [comment]
This issue is actually because of how microsoft is doing application aliases.  To run the newer version of windows terminal I had to disable the old one launched via the alias.  The exe itself is 0 bytes if you look.

![image](https://user-images.githubusercontent.com/684524/125195439-9d8e1800-e223-11eb-8e4d-7e716d7e9625.png)

**Comment by flyingpie** [comment]
@justinledwards Thank you so much for reporting this! Saved us a ton of time :D I'll add this to the docs.
