### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by mikef-nl** [flyingpie/windows-terminal-quake#7]
Could be nice to have it configurable via a json file for:
Hotkeys
Timer for the dropdown

**Comment by Alessandro-D** [comment]
Indeed, especially for changing the main hotkey.
Is there any way to do that right now?

**Comment by flyingpie** [comment]
@Alessandro-D Not yet, but definitely a good idea. I'll try to whip something up today.

**Comment by sanconley** [comment]
Any update on this?

**Comment by ukWaqas** [comment]
Two main features that should be customisable:
1. Semi transparent, 
2. Come down half the screen

**Comment by mikef-nl** [comment]
Looks like someone already got that far https://github.com/flyingpie/windows-terminal-quake/pull/8

**Comment by insign** [comment]
> @Alessandro-D Not yet, but definitely a good idea. I'll try to whip something up today.

Today, LOL

Looks like some MIB kidnapped him

**Comment by Croydon** [comment]
Everyone has too little time and too much to do. Things happen 😄

**Comment by flyingpie** [comment]
So I was full-on taken by the MIB. Good news is that I don't need any colonoscopy any time soon.

@mikef-nl @Alessandro-D @sanconley @ukWaqas @insign @Croydon

Pre release v0.4 adds a settings file with:
- Customizable hotkeys
- Toggle notifications (when the app starts and when the settings file is reloaded
- Toggle duration (how long it takes for the terminal to come down/go back up
- Vertical screen coverage (how much of the screen is taken up by the terminal

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.4

Please let me know if this is to your liking and whether you have any suggestions/encounter bugs.

**Comment by Croydon** [comment]
Do hotkeys need a modifier? Is it expect to work if I want to have the toggling feature on e.g. `F8`?

**Comment by nstrelow** [comment]
OR F1

Would be nice to have an option to only set one key.

**Comment by Croydon** [comment]
Actually, it works for me

My mistake previously was that I put it into a subdirectory of the programs directory which requires admin rights. Executing quake withOUT admin rights causes then that it can't read the config

Very tiny potential improvement: When quake shows the hotkey in the notification it shows `0+F8` when it is just `F8`

**Comment by nstrelow** [comment]
how did you set it to only one key?

**Comment by Croydon** [comment]
Do something like

```
{
	// The keys that can be used to toggle the terminal
	"HotKeys": [
		{
                     "Key": "F8"
		}
	],
```

**Comment by flyingpie** [comment]
@ukWaqas I'm continuing the transparency part in #11 

There is a pre-release here: https://github.com/flyingpie/windows-terminal-quake/releases/tag/v0.5

![image](https://user-images.githubusercontent.com/1295673/90699843-a335e480-e284-11ea-98b2-989c063ac447.png)
