### ISSUE TITLE
Setting key to only F12 doesn't seem to work

### ISSUE THREAD

**Issue by Shuaiouke** [flyingpie/windows-terminal-quake#70]
I would like the key to be set to F12 so it behaves just like in linux, my config is simply
	"HotKeys": [
		{
			"Key": "F12"
		}
	]
but it didn't work, i have tried other keys in it's place and it seems fine, I think it's only the function keys that are broken

**Comment by lpuglia** [comment]
F12 on windows is a special key used in debugging, for some reasons it is set system-wide, you may want to disable this windows shortcut first:
https://conemu.github.io/en/GlobalHotKeys.html#Using_F12_as_global_hotkey

**Comment by flyingpie** [comment]
@lpuglia Thank you for pointing this out, would have taken me forever :D

@Shuaiouke Can you confirm that this fixes the problem for you as well?

**Comment by flyingpie** [comment]
The cause and a solution for this problem is added to the [docs](https://flyingpie.github.io/windows-terminal-quake/settings/hotkeys/#f12-as-a-hotkey), closing this issue.
