### ISSUE TITLE
After adding json config the app fails to start - Cannot start: 'Value cannot be null. Parameter name: source'.

### ISSUE THREAD

**Issue by maxim-shlain** [flyingpie/windows-terminal-quake#72]
I've added following config file:
C:\Users\%USERNAME%\windows-terminal-quake.json

with below content:
{
    "AlwaysOnTop": true,
    "HideOnFocusLost": false,
    "HorizontalScreenCoverage": 80,
    "VerticalScreenCoverage": 80,
    "StartHidden": true
}

when I start the app, the terminal launches but the quake mode does not work

the following error appears:
![image](https://user-images.githubusercontent.com/74252364/111136070-fdcac100-8585-11eb-9fc4-05d8d553fedb.png)

Workaround:
Remove the config file, start the app and bring the file back. The app loads the config on-the-fly and works as expected

**Comment by maxim-shlain** [comment]
Terminal preview directly starts successfully
Nothing special in event viewer

**Comment by rafiazman** [comment]
Just ran into this same issue with the following config in the same direction (inside `C:\Users\%USERNAME%\`

```
{
  "AlwaysOnTop": true,
  "HorizontalScreenCoverage": 100,
  "ToggleDurationMs": 10,
  "ToggleAnimationFrameTimeMs": 15,
  "Opacity": 80
}
```

**Comment by flyingpie** [comment]
@maxim-shlain @rafiazman Thank you for your feedback, I have added a new prerelease version of v1.2.0 where this issue should be solved.

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

It was because of the "Hotkeys"-setting no longer receiving a default when none is set.

I hope this fixes the issue :)

**Comment by maxim-shlain** [comment]
Works for me on https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

Thanks
