### ISSUE TITLE
Toggle animation is weird on vertically-stacked monitors

### ISSUE THREAD

**Issue by marxjohnson** [flyingpie/windows-terminal-quake#74]
I have 2 monitors, one above the other. If I press the key to reveal windows-terminal-quake on my bottom monitor, the window appears at the bottom of my top monitor, then slides down to the bottom one. This looks really odd.

I have worked around this by setting ToggleDurationMs and ToggleAnimationFrameTimeMs to 15, effectively disabling the animation.

**Comment by flyingpie** [comment]
@marxjohnson Thank you for reporting this! It's actually showing the hacky trick of how the toggle works, by moving the entire window off to the top.

I'm not sure of how to fix this, as I haven't actually taken into account vertically-stacked monitors tbh.

Do you think it would be acceptable to have it fly in from the side or the bottom or something?

**Comment by marxjohnson** [comment]
I'm not really sure what the "right" solution would be. You could make it fly in from another side, but presumably that would have the same problem if there's another monitor to that side?

Another possibility might be an option to have it appear in place, but fade in from 0 to the configured opacity?

**Comment by flyingpie** [comment]
@marxjohnson I'll try and see what the fade does, not sure if it's gonna be fast enough though. What does your configuration look like?

**Comment by shanselman** [comment]
I have this issue also. What about **resizing** the window vertically until it gets small, then hiding it.

**Comment by flyingpie** [comment]
@shanselman Thank you for your suggestion! I've made a first test of this, and it seems to work very nicely.

I'm still making this non-horrendous, but in the mean time, I'd love for you guys (@marxjohnson) to check out the test version:
https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

Over time, I've had people report some issues across different computers and -monitor setups, so some feedback using multiple setups would be great :)

**Comment by shanselman** [comment]
That looks awesome! The only weird part is that if you have two monitors, 1 and 2, top and bottom. 1 is 1080p and 2 is 4k. If you activate this hotkey while on the bottom monitor, it looks great. While on the top, it is half size. See video.

https://1drv.ms/v/s!AiwVcXM2pwbNibITNh_w1wCIgyL88A?e=wuJbaU

**Comment by flyingpie** [comment]
Thanks for the quick response, could you post your settings file please?

**Comment by marxjohnson** [comment]
@flyingpie I've tried out that build, the animation looks good, but I can't get it to appear on my bottom monitor, so I can't really tell if it resolves the problem! I've attached my config file. I've also tried "AtIndex" and "Primary" for the "PreferMonitor" option, but it doesn't seem to help.
[windows-terminal-quake.zip](https://github.com/flyingpie/windows-terminal-quake/files/6383000/windows-terminal-quake.zip)

**Comment by flyingpie** [comment]
@marxjohnson @shanselman I've updated the release, messed around with different monitor configurations, and I'm very curious to know if stuff is working better for you now:

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

Thanks again for both your feedback, very useful to allow more monitor configurations :)

**Comment by jake-harris** [comment]
I'm getting a JSON parsing error when starting up from the config file.

![image](https://user-images.githubusercontent.com/5045536/116341472-d9bdea80-a795-11eb-9178-9292763b6851.png)

Here's my log:

````
2021-04-27 20:13:20.014 -07:00 [INF] Windows Terminal Quake started
2021-04-27 20:13:20.219 -07:00 [INF] Got process with id '6904' and name 'WindowsTerminal' and title 'Windows PowerShell'.
2021-04-27 20:13:20.234 -07:00 [INF] Open
2021-04-27 20:13:20.235 -07:00 [INF] Focus gained
2021-04-27 20:13:20.242 -07:00 [INF] Selecting screen with cursor.
2021-04-27 20:13:20.370 -07:00 [WRN] Error: Value cannot be null.
Parameter name: source
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at WindowsTerminalQuake.Program.Main(String[] args)
2021-04-27 20:13:56.439 -07:00 [INF] Focus lost
2021-04-27 20:13:56.465 -07:00 [INF] Close
2021-04-27 20:13:56.481 -07:00 [INF] Selecting screen with cursor.
````

**Comment by flyingpie** [comment]
@jake-harris Thank you for reporting this, could you share your settings file?

**Comment by marxjohnson** [comment]
> @marxjohnson @shanselman I've updated the release, messed around with different monitor configurations, and I'm very curious to know if stuff is working better for you now:
> 
> https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

@flyingpie This works well for me!

**Comment by jahsome** [comment]
> @jake-harris Thank you for reporting this, could you share your settings file?

I realized the config I was using was not the one I thought. When I used the correct config things loaded for me. As of know things are working smoothly, I'll post if I have any issues.

**Comment by flyingpie** [comment]
I'm closing this issue since the new default way of toggling uses resize, which should fix the problem.

If anyone encounters a scenario where this is still causing trouble, feel free to re-open this issue, or create a new one.

It's also possible to revert to the old "Move"-method, through the ["ToggleMode"](https://flyingpie.github.io/windows-terminal-quake/settings/toggle-animation/#toggle-mode) setting.
