### ISSUE TITLE
Feature Request: Option to also close WT when exiting Terminal Quake from system tray

### ISSUE THREAD

**Issue by ninjaeon** [flyingpie/windows-terminal-quake#82]
Currently, exiting Windows Terminal Quake (WTS) from the system tray brings the Windows Terminal (WT) window to the forefront without exiting WT.

I often run desktop shortcuts that simultaneously open WTQ and WT with an executable or batch file running in command prompt.  When I want to stop the program from running and exit WT, I first have to pull down WTQ and then either click the close window button or press Alt+F4 to close both WT and WTQ at the same time.

I suggest there be an option for WT to also exit at the same time when exiting WTQ via the system tray.

**Comment by flyingpie** [comment]
@ninjaeon Thank you for reporting this!

I think that's a great idea, milestoned for 1.3.
