### ISSUE TITLE
Adding a "shortcut" parameter to the Scoop Package 

### ISSUE THREAD

**Issue by mentofa123** [flyingpie/windows-terminal-quake#84]
The scoop package scheme has a paramter for providing shortcuts. 
This could be used for the windows-terminal-quake.exe provide a better shortcut in the startmenu. 

The now produced shim always opens a powershell window to execute the shim script and let it stay open. 

I already updated the json file and can create a pull request if this "feature" is wanted :)

**Comment by flyingpie** [comment]
@mentofa123 Thank you for reporting this, I would very much be interested in a PR :)

**Comment by mentofa123** [comment]
@flyingpie  added a pull request :)
