### ISSUE TITLE
"Main window handle not accessible" when having windows-terminal-quake start WT Preview 1.9

### ISSUE THREAD

**Issue by bllngr** [flyingpie/windows-terminal-quake#86]
I just updated WT Preview to version 1.9.1445. Now, windows-terminal-quake cannot start WT anymore with the following error:

![image](https://user-images.githubusercontent.com/303458/119632847-79ac7980-be11-11eb-86d7-9396bd51c4cf.png)

WTQ works as before when WT is manually started before it.

**Comment by pnuzhdin** [comment]
I have the same issue. Meanwhile, WT Preview now has its own quake mode but I found it less useful rather than windows-terminal-quake because it doesn't support tabs and customized way less.

**Comment by pnuzhdin** [comment]
Also, I found the following workaround (for me windows-terminal-quake just didn't start at all):
1. Start Windows Terminal Preview before starting windows-terminal-quake.
2. Start windows-terminal-quake.

Now windows-terminal-quake works as expected.

**Comment by bllngr** [comment]
For some reason, it doesn't happen anymore for me. I didn't upgrade neither WT nor WTQ, but I'm not getting the error anymore.

@pnuzhdin, @pgarlinsiki, does it still happen for you? Otherwise, I would close the ticket.

**Comment by pgarlinski** [comment]
@bllngr Odd...works for me today as well. No updates on my end either.

**Comment by bllngr** [comment]
All right, let's close this. Feel free to reopen if the bug reappears.

**Comment by pnuzhdin** [comment]
Yep, it seems fixed in WT Preview 1.9.1523.0. It updated automatically from the Windows Store and now works as expected.

**Comment by flyingpie** [comment]
Thank you guys for reporting this and thanks to @bllngr for providing feedback while I was slacking off ❤️

Like he already mentioned, feel free to re-open if the poop hits the fan again.
