### ISSUE TITLE
Question:  Terminal Preview support for Quakemode?

### ISSUE THREAD

**Issue by mkanet** [flyingpie/windows-terminal-quake#87]
Does anyone know if it's possible to do Quakemode in Terminal Preview the same way I can with Windows-Terminal-Quake or ConEmu?  [I tried various settings in Terminal Preview](https://github.com/microsoft/terminal/issues/653#issuecomment-848990087); but, it appears it doesn't work correctly or has missing capabilities that are available only in Windows-Terminal-Quake.

BTW: Thank you for Windows-Terminal-Quake, its the only way I can get MS Terminal to work just like ConEmu quakestyle.  However, it would be nice to be able to do this natively in MS Terminal.

**Comment by DHowett** [comment]
The correct place to make feature requests for Terminal is not on the excellent repository of somebody who's writing a tool that _works with Terminal_. It's on the Terminal repository. :smile:

We're still working on quake mode, but you can always unbind our version of <kbd>Win+`</kbd> and let the version from this repository "win". That way, you get the best of both worlds!

**Comment by mkanet** [comment]
> The correct place to make feature requests for Terminal is not on the excellent repository of somebody who's writing a tool that _works with Terminal_. It's on the Terminal repository. 😄
> 
> We're still working on quake mode, but you can always unbind our version of Win+` and let the version from this repository "win". That way, you get the best of both worlds!

Thanks.  But, I wasn't asking for any feature requests.  I just wanted to verify if the new quake mode in Terminal Preview can currently reproduce what Windows-Terminal-Quake does currently.  I wasn't able to.  I'm not sure if that's because I have the wrong settings, or there are missing quake features in MS Terminal Preview.  I already tried asking there; but, it appears they may not be familiar with Windows-Terminal-Quake or ConEmu.

**Comment by DHowett** [comment]
We definitely can’t match the flexibility of this project yet :)

**Comment by DHowett** [comment]
(We are, however, quite familiar with ConEmu!)

**Comment by mkanet** [comment]
Thanks.  I'll just continue using Window-Terminal-Quake, since it can match what ConEmu Quake Style does perfectly. I'm guessing it's just not possible in MS Terminal Preview yet. I haven't been able to confirm it, but it sounds like that might be the case.

**Comment by DHowett** [comment]
I am from the Terminal team and I am here confirming this for you.
