### ISSUE TITLE
float values no longer accepted for *ScreenCoverage

### ISSUE THREAD

**Issue by tdy** [flyingpie/windows-terminal-quake#95]
The `*ScreenCoverage` settings and terminal bounds are now `int`:

https://github.com/flyingpie/windows-terminal-quake/blob/d6420c380a61dc7b89e851d0f82e24c8aa3bf505/windows-terminal-quake/Settings/SettingsDto.cs#L47

https://github.com/flyingpie/windows-terminal-quake/blob/d6420c380a61dc7b89e851d0f82e24c8aa3bf505/windows-terminal-quake/Settings/SettingsDto.cs#L152

https://github.com/flyingpie/windows-terminal-quake/blob/d6420c380a61dc7b89e851d0f82e24c8aa3bf505/windows-terminal-quake/TerminalBoundsProviders/MovingTerminalBoundsProvider.cs#L16-L17

Previously I was using a float (100.75) to make it flush as described in https://github.com/flyingpie/windows-terminal-quake/issues/12#issuecomment-678488362 and the settings comments:

https://github.com/flyingpie/windows-terminal-quake/blob/d6420c380a61dc7b89e851d0f82e24c8aa3bf505/windows-terminal-quake/windows-terminal-quake.json#L65-L68

Was this a regression or intentional? I'm not able to make the quake window flush with only `int` settings.

---

Version: [windows-terminal-quake-1.2.0-2021-05-16_1602 binary release](https://github.com/flyingpie/windows-terminal-quake/releases/download/v1.2.0/windows-terminal-quake-1.2.0-2021-05-16_1602.zip)

Note that I think this change was intended only for 1.3.0+ (it doesn't exist in 1.2.0's [source tree](https://github.com/flyingpie/windows-terminal-quake/tree/v1.2.0) and [source zip](https://github.com/flyingpie/windows-terminal-quake/archive/refs/tags/v1.2.0.zip)), but the change is already in effect in the 1.2.0 binary.

**Comment by flyingpie** [comment]
@tdy Good catch! Will fix this in the next release.

**Comment by flyingpie** [comment]
Fixed in the latest v1.3.0 preview.

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.3
