### ISSUE TITLE
Weird input focus behavior on v1.2.0

### ISSUE THREAD

**Issue by fmiqbal** [flyingpie/windows-terminal-quake#96]
Recently I upgrade to v1.2.0 from v1.1.1 but I found weird behavior that I can confirm not from windows terminal, already try windows terminal 1.7, 1.8, 1.9-preview, but no avail. I use full screen, always on top, hide on lost focus

The problem is when I focus other window and the quake hide, when I toggle open again, the cursor become on top rather than showing previous scroll, expected like this:
<details>

![image](https://user-images.githubusercontent.com/8409391/123556344-fd60d980-d7b4-11eb-87b1-c5b0cdac96aa.png)
![image](https://user-images.githubusercontent.com/8409391/123556350-02258d80-d7b5-11eb-8f92-8eb297d812bc.png)

</details>

But instead got this
<details>

![image](https://user-images.githubusercontent.com/8409391/123556381-28e3c400-d7b5-11eb-928f-233dc7caf9a0.png)
![image](https://user-images.githubusercontent.com/8409391/123556433-63e5f780-d7b5-11eb-9cc8-cdb94fe1a867.png)

</details>
The cursor always on top and hide everything before it, I need to scroll to see previous command and result. This also happen when I start to type, the window instantly focus to current input, and make the input on top, again, hiding everything before it.

v1.1.1 doesn't have this issue

Quake config, but I recently learned that using vanilla config also have this issue:
```
{
	"HotKeys": [
		{
			"Modifiers": "Alt",
			"Key": "Escape"
		}
	],
	"Notifications": true,
	"Opacity": 90,
	"ToggleDurationMs": 15,
	"ToggleAnimationFrameTimeMs": 15,
	"VerticalOffset": 0,
	"VerticalScreenCoverage": 100,
	"HorizontalAlign": "Center",
	"HorizontalScreenCoverage": 100,
	"HideOnFocusLost": true,
	"AlwaysOnTop": true,
	"StartHidden": false,
	"PreferMonitor": "WithCursor",
	"MonitorIndex": 1,
	"Logging": true
}
```

Windows 10 Version Dev (OS Build 21390.2025)

**Comment by fmiqbal** [comment]
![weird](https://user-images.githubusercontent.com/8409391/123556798-8f69e180-d7b7-11eb-8369-d1a145df5031.gif)

**Comment by flyingpie** [comment]
@fmiqbal Thank you for reporting this issue! I think this might be due to the recently added different toggle mode, could you try to add the following and see if it changes anything?

```json
{
	"ToggleMode": "Move"
}
```

**Comment by fmiqbal** [comment]
Nice, thank you, that's fixed it

**Comment by flyingpie** [comment]
The default toggle mode has been changed to "Move", on version 1.3.0, to prevent this issue, seeing that there are perhaps more cases of this then vertical monitor setups, which was the reason for the "Resize" mode.
